categoryToNames = {"International": [
    "International",
    "World Foods",
    "Chinese",
    "Indian",
    "Japanese",
    "Korean",
    "Other Countries",
    "South East Asian",
    "Thai",
    "UK",
    "USA"
],
    "Fruit and Vegetables": [
        "Fruit & Veg",
        "Fresh Fruit",
        "Fresh Salad & Herbs",
        "Fresh Vegetables",
        "In Season",
        "Prepared Fruit & Veg",
        "The Odd Bunch",
        "Fruit & Vegetables",
        "Fresh Cut Fruit",
        "Fresh Herbs",
        "PrePacked Fresh Fruit",
        "PrePacked Fresh Vegetables",
        "Salad Bags",
        "Frozen Fruit",
        "Fruit Snacks",
        "Vege Snacks",
        "Olives",
        "Pickles",
        "Canned & Dried Vegetables",
        "Canned Fruit",
        "Vegetable Juices",
        "Fresh Salads",
        "Vege Bags",
        "Freshly Ground Herbs"
    ],
    "Organic": [
        "Organic",
        "Fresh Organic Milk",
        "Organic & Gluten Free"
    ],
    "Meat": [
        "Meat & Poultry",
        "Meat",
        "BBQ Meat",
        "Beef",
        "Chicken & Poultry",
        "Lamb",
        "Mince & Patties",
        "Offal & Bones",
        "Pork",
        "Roast Meat",
        "Sausages",
        "Venison & Game",
        "Butchery",
        "Fresh Beef & Lamb",
        "Fresh Chicken & Poultry",
        "Fresh Pork",
        "Fresh Sausages",
        "Fresh Venison & Game Meat",
        "PreCooked Sausages",
        "PrePacked Beef & Lamb",
        "PrePacked Chicken & Poultry",
        "PrePacked Sausages",
        "Bacon",
        "Continental Sausage & Salami",
        "Ham & Pork",
        "PreCooked Beef & Lamb",
        "PreCooked Chicken & Poultry",
        "Frozen Meat",
        "Frozen Beef Lamb & Pork",
        "Frozen Chicken & Poultry",
        "Meat Snacks",
        "Canned Meat",
        "PrePacked Pork"
    ],
    "Vegan & Vegetarian": [
        "Vegan & Vegetarian",
        "Vegan",
        "Pams Plant Based",
        "Vegan range",
        "Meat Free",
        "Frozen Vegetarian",
        "Vegetarian",
        "Dairy & Lactose Free",
        "Plant based alternatives",
        "Frozen Meat Alternatives",
        "Rice Cakes",
        "Rice Crackers",
        "Fruit Snacks",
        "Vege Snacks",
        "Coconut Cream & Milk",
    ],
    "Sauces and Dressings": [
        "sauces and Dressings",
        "Condiments & Dressings",
        "Aioli",
        "Barbeque Sauces",
        "Chilli & Pepper Sauces",
        "Chutneys",
        "Fruit Sauces",
        "Mayonnaise",
        "Mint Sauces",
        "Mustards",
        "Salad Dressings",
        "Worcestershire Sauces",
        "Sauces & Pastes",
        "Sauces Stock & Marinades",
        "Chilled Pasta Sauces",
        "Marinades",
        "Packet Sauces",
        "Pasta Sauces",
        "Simmer & Stir-Through Sauces",
        "Soy Sauce",
        "Specialty Sauces",
        "Stir Fry Sauces",
        "Dips & Salsas",
        "Relish",
        "Vinegars",
        "Curry Pastes & Sauces",
        "Gravies",
        "Tomato Sauces",
        "Tartare & Seafood Sauces"
    ],
    "Bulk Buys": [
        "Bulk Buys",
        "Bulk Foods",
        "Bulk & Loose Foods",
        "Bulk Breakfast Cereals",
        "Bulk Confectionery",
        "Bulk Dried Fruit",
        "Bulk Nuts",
        "Bulk Seeds Legumes & Grains",
        "Bulk Snacks & Mixes"
    ],
    "Fish and Seafood": [
        "Fish and Sea Food",
        "Fish & Seafood",
        "Fresh Fish",
        "Prawns & Seafood",
        "Salmon",
        "Seafood",
        "Fresh Fish Fillets & Steaks",
        "Fresh Seafood",
        "Fresh Shellfish",
        "Fresh Smoked Fish",
        "Frozen Fish & Seafood",
        "Seafood Salad",
        "Frozen Seafood",
        "Frozen Fish",
        "Canned Fish",
        "Fresh Fish Heads",
        "Fresh Whole Fish"
    ],
    "Butter & Spreads": [
        "Butter & Spreads",
        "Dips Hummus & Nibbles",
        "Dips Pesto & Pate",
        "Hummus",
        "Jams Honey & Spreads",
        "Honey",
        "Jam & Marmalade",
        "Marmite & Vegemite",
        "Nut Spreads",
        "Savoury Spreads",
        "Sweet Spreads",
        "Salad & Cooking Oils",
        "Avocado Oils",
        "Olive Oils"
    ],
    "Dairy and Eggs": [
        "Dairy and Eggs",
        "Cheese",
        "Long Life Milk",
        "Milk & Cream",
        "Yoghurt & Desserts",
        "Eggs",
        "Flavoured Milk",
        "Fresh Cream",
        "Fresh Milk",
        "Fresh Organic Milk",
        "Long Life Milk & Milk Powder",
        "Sour Cream & Crème Fraiche",
        "Yoghurt & Dairy Food",
        "Yoghurt Bases",
        "Cheese Blocks",
        "Cheese Slices",
        "Cottage Cheese",
        "Cream Cheese",
        "Grated Cheese",
        "Specialty Cheeses",
        "Canned Milk & Cream",
        "Milk Drink Mixes"
    ],
    "Deli": [
        "Deli",
        "Deli Meats & Seafood",
        "Deli Salads",
        "Fresh Deli Savouries",
        "Deli Salads & Cooked Meats",
        "Deli Meats",
        "Deli Cheeseboards",
        "Deli Specialty Cheeses",
        "Deli Cabinet Cheeses",
        "Fridge & Deli"
    ],
    "Drinks": [
        "Drinks",
        "Juice & Drinks",
        "Low & no alcohol",
        "Coffee",
        "Juice & Cordial",
        "Soft Drinks & Sports Drinks",
        "Tea & Milk Drinks",
        "Water",
        "Cold Drinks",
        "Hot Drinks",
        "Black Teas",
        "Chai Teas",
        "Chocolate Milk Drink Mixes",
        "Coffee Additives & Filters",
        "Coffee Capsules",
        "Coffee Flavoured Sachets",
        "Fresh Coffees",
        "Fruit & Herbal Teas",
        "Green Teas",
        "Instant Coffees",
        "Malt Milk Drink Mixes",
        "Frozen Fruit & Drink",
        "Chilled Fruit Juices",
        "Coconut Water",
        "Drinking Yoghurt & Smoothies",
        "Flavoured Water",
        "Fruit Drinks & Juices",
        "Iced Teas",
        "Powdered Drinks",
        "Soft Drinks",
        "Sparkling Juices",
        "Sparkling Water",
        "Sports & Energy Drinks",
        "Non Alcoholic",
        "Vegetable Juices",
        "Squash Syrups & Cordials",
        "Milk Drink Mixes",
        "Still Water",
        "Coffee Substitutes",
        "Brewing Supplies"
    ],
    "Easy Meals": [
        "Easy Meals",
        "Fresh Pastas",
        "Instant Rices",
        "Rice Meals",
        "Frozen Meals & Snacks",
        "Frozen Dessert Pastries",
        "Frozen Ready Meals",
        "Frozen Pies",
        "Pizza Pastry & Bread",
        "Breakfast On The Go",
        "Novelty Bars & Singles",
        "Baked Beans & Spaghetti",
        "Canned & Prepared Foods",
        "Tinned Foods",
        "Pasta Pizza & Pastry",
        "Prepared Meals & Sides",
        "Meal Kits",
        "Meal Spot",
        "Ready to Cook",
        "Mexican",
        "Noodle Meals",
        "Pasta Meals",
        "Simply DINNER",
        "Ready to Eat",
        "Ready to Heat",
        "Canned Soup",
        "Chilled Pies & Pastries",
        "Chilled Soups",
        "Packet Soup",
        "Pizza & Pizza Bases",
        "Ready Meals"
    ],
    "Bakery": [
        "Ice Cream Cones & Wafers",
        "Bakery",
        "Bagels Crumpets & Pancakes",
        "Baked In Store",
        "Buns Rolls & Bread Sticks",
        "Cakes Muffins & Desserts",
        "Gluten Free Bakery",
        "Low Carb & Keto Bakery",
        "Pastries Croissants & Biscuits",
        "Sliced & Packaged Bread",
        "Wraps Pita & Pizza Bases",
        "Hot Cross Buns",
        "Fresh Foods & Bakery",
        "Biscuits & Slices",
        "Bread Rolls & Buns",
        "Cakes & Muffins",
        "Fresh Biscuits & Slices",
        "Fresh Breads & Rolls",
        "Fresh Cakes & Muffins",
        "Fresh Desserts & Pastries",
        "Garlic & Herb Breads",
        "Muffin Splits & Crumpets",
        "Pies & Pastries",
        "Sliced Bread",
        "Specialty Breads",
        "Wraps & Pita Breads",
        "Organic & Gluten Free",
        "Frozen Dessert Pastries",
        "Frozen Pastry",
        "Frozen Pies",
        "Baking",
        "Baking Supplies & Sugar",
        "Pizza Pastry & Bread",
        "Baking Additives",
        "Baking Mixes",
        "Baking Nuts & Seeds",
        "Baking Syrups",
        "Breadcrumbs & Coatings",
        "Cooking Chocolate",
        "Dried Fruit",
        "Essences & Colourings",
        "Flour",
        "Icing & Decorating",
        "Sugar",
        "Sugar Substitutes",
        "Dessert Pastries",
        "Frozen Bread & Dough"
    ],
    "Kids": [
        "Baby & Child",
        "Kids and Babies",
        "Baby Food",
        "Bottles Toys & Accessories",
        "For Mum",
        "Formula",
        "Nappies & Wipes",
        "Baby Toddler & Kids",
        "Baby Care",
        "Baby Bathing & Skin Care",
        "Baby Dental Care",
        "Baby Formula & Toddler Food",
        "Baby Hair Care",
        "Baby Health",
        "Baby Wipes",
        "Nappies & Changing",
        "Nursing & Feeding",
        "Toys & Recreation"
    ],
    "Pets": [
        "Pet",
        "Birds Fish & Small Animals",
        "Cats",
        "Dogs",
        "Pet health & accessories",
        "Pets",
        "Pet Supplies",
        "Cat Accessories",
        "Cat Food",
        "Dog Food",
        "Dog Treats",
        "Bird Supplies",
        "Cat Treats",
        "Dog Accessories",
        "Pet Accessories",
        "Pet Treatments",
        "Small Animal Supplies",
        "Fish & Aquatic Pet Supplies"
    ],
    "Cleaning, Laundry And Bathroom": [
        "Cleaning Products",
        "All Purpose Cleaners",
        "Bathroom & Shower Cleaners",
        "Bleaches",
        "Carpet & Floor Cleaners",
        "Cleaning Accessories",
        "Dishwasher Detergents",
        "Dishwasher Rinse & Clean",
        "Dishwashing Liquid",
        "Furniture & Metal Polishes",
        "Glass Cleaners",
        "Kitchen Cleaners",
        "Paper Towels",
        "Brushes",
        "Glue & Adhesives",
        "Air Fresheners & Deodorisers",
        "Household",
        "Disposable Tableware",
        "Pest & Insect Control",
        "Rubbish & Vacuum Bags",
        "Tissues & Toilet Paper",
        "Laundry",
        "Fabric Softeners",
        "Laundry Liquid & Capsules",
        "Laundry Powders",
        "Laundry Supplies",
        "Pre Wash Stain Removers",
        "Car Care",
        "Shoe Care",
        "Fine Fabric Washers",
        "Laundry Soap",
        "Washing Machine Cleaners",
        "Tissues & Cotton Buds",
        "Cleaning",
        "Bags",
        "Bathroom"
    ],
    "Personal Care": [
        "Health & Body",
        "Personal Care",
        "Bath Shower & Soap",
        "Contraception & Pregnancy",
        "Dental & Oral Care",
        "Eye & Ear Care",
        "Hair Care",
        "Make Up & Nail Care",
        "Medical & First Aid",
        "Period & Continence Care",
        "Shaving & Hair Removal",
        "Skin Care & Deodorant",
        "Beauty & Grooming",
        "Deodorants",
        "Face & Lip Skin Care",
        "Hair Care & Treatments",
        "Hair Colouring",
        "Hair Styling & Accessories",
        "Hand & Body Care",
        "Makeup & Cosmetics",
        "Oral Health",
        "Suncare & Self Tan",
        "Health & Wellness",
        "Adult Care",
        "Allergy & Sinus",
        "Cough Cold & Flu",
        "Digestion Nausea & Laxatives",
        "Family Planning",
        "First Aid",
        "Pain Relief",
        "Sanitary Protection",
        "Stop Smoking",
        "Vitamins & Supplements",
        "Wellness & Sports Nutrition",
        "Foot Care",
        "Vitamins & Nutrition",
        "Sports & Fitness"
    ],
    "Snacks": [
        "Snacks",
        "Biscuits & Crackers",
        "Assorted Biscuits & Crackers",
        "Biscuits & Cookies",
        "Chocolate Biscuits",
        "Crackers",
        "Crème & Jam Biscuits",
        "Gourmet Biscuits & Crackers",
        "Snack Foods",
        "Snacks & Sweets",
        "Chips",
        "Corn Chips",
        "Meat Snacks",
        "Popcorn",
        "Potato Chips",
        "Snack Mixes",
        "Rice Cakes",
        "Rice Crackers",
        "Fruit Snacks",
        "Vege Snacks",
        "Plain Sweet Biscuits",
        "Bread Snacks",
        "Cereal & Snack Bars",
        "Muesli Bars",
        "Nut Bars & Snacks",
        "Nutritional Bars",
        "Chewing Gum & Mints",
        "Confectionery",
        "Boxed Chocolates",
        "Chocolate Blocks",
        "Chocolate Family Bags",
        "Lollies Family Bags",
        "Ready To Serve Puddings",
        "Desserts",
        "Novelty Bars & Singles",
        "Gourmet Confectionery",
        "Chilled Custards",
        "Ice Blocks & Ice Pops"
    ],
    "Baking": [
        "Jelly & Powdered Desserts",
        "Cooking & Bakeware",
        "Food Storage",
        "Food Wraps & Bags",
        "Kitchenware"
    ],
    "Frozen": [
        "Frozen",
        "Frozen Fish & Seafood",
        "Frozen Items",
        "Frozen Desserts",
        "Frozen Fruit & Drink",
        "Frozen Meals & Snacks",
        "Frozen Meat",
        "Frozen Meat Alternatives",
        "Frozen Seafood",
        "Frozen Vegetables",
        "Chilled Frozen & Desserts",
        "Frozen Bavarians & Cheesecake",
        "Frozen Fries & Potatoes",
        "Frozen Pizza & Bases",
        "Frozen Savouries",
        "Ice",
        "Ice Cream & Sorbet",
        "Frozen Foods",
        "Frozen Puddings",
        "Ice Cream & Frozen Yoghurt"
    ],
    "Alcoholic": [
        "Beer & Wine",
        "Alcohol",
        "Beer",
        "Cider",
        "Red wine",
        "Rose wine",
        "Sparkling & dessert wine",
        "White wine",
        "Liquorice",
        "Beer Cider & Wine",
        "Beer & Cider Awards",
        "Cider & Alcoholic Gingerbeer",
        "IPA",
        "Lager & Pilsner",
        "Pale Ale",
        "Beer & Cider",
        "American-style Ale",
        "Apple & Pear Cider",
        "Craft Beer",
        "Lager",
        "Low & No Alcohol Beers",
        "Specialty & Flavoured Beer",
        "Stout Porter & Black Beer",
        "Wine",
        "Cabernet",
        "Cask Wine",
        "Champagne & Sparkling Wine",
        "Chardonnay",
        "Low & No Alcohol Wines",
        "Merlot",
        "Other Red Wine",
        "Other White Wine",
        "Pinot Gris",
        "Pinot Noir",
        "Rose",
        "Fruit & Flavoured Cider",
        "Seltzer",
        "Mixers",
        "Shiraz",
        "Sauvignon Blanc",
        "British-style Ale",
        "European-style Ale",
        "Sake"
    ],
    "Pantry": [
        "Pantry",
        "Sauces & Pastes",
        "Soy Sauce",
        "Pasta Sauces",
        "Long Life Milk & Milk Powder",
        "Herbs Spices & Stock",
        "Spices & Seasonings",
        "Oil Vinegar & Condiments",
        "Pasta Noodles & Grains",
        "Breakfast Cereals",
        "Gourmet Oils & Condiments",
        "Olives & Antipasti Mixes",
        "Pantry",
        "Specialty Dry Goods",
        "Olives",
        "Pickles",
        "Specialty Grains & Seeds",
        "Hot Cereals",
        "Muesli",
        "Pasta Rice & Noodles",
        "Dried Pastas",
        "Noodles",
        "Cold Cereals",
        "Flake/Fibre Cereals",
        "Basmati Rices",
        "Jasmine Rices",
        "Long Grain Rices",
        "Short & Medium Grain Rices",
        "Wild & Coloured Rices",
        "Curry Pastes & Sauces",
        "Gravies",
        "Tomato Pastes & Purees",
        "Tomato Sauces",
        "Avocado Oils",
        "Coconut Oils",
        "Nut & Seed Oils",
        "Oil Sprays",
        "Olive Oils",
        "Other Oils",
        "Rice Bran Oils",
        "Vegetable Oils",
        "Chilli & Paprika",
        "Dried Herbs",
        "Dried Spices",
        "Garlic & Ginger",
        "Salt & Pepper",
        "Canned Desserts",
        "Canned Items",
        "Canned & Dried Vegetables",
        "Canned Fruit",
        "Canned Meat",
        "Canned & Prepared Foods",
        "Tinned Foods",
        "Canned Fish",
        "Cooking Fat"
    ],
    "Other": [
        "Shop Fresh Deals",
        "Easter eggs and chocolates",
        "Easter feast essentials",
        "Easter",
        "Christmas",
        "Insect Repellent",
        "Garage & Outdoor",
        "Light Bulbs",
        "Hooks",
        "Tape",
        "Electrical",
        "Fire Needs",
        "Homeware",
        "Manchester",
        "Party Supplies",
        "Stationery & Entertainment",
        "Newspapers",
        "Stationery & Craft",
        "Tobacco Papers & Filters",
        "BBQ",
        "Gardening Supplies",
        "Clothes Pegs",
        "Magazines",
        "Other",
        "Clothing & Accessories",
        "Entertainment & Gifts",
        "Garden & Garage",
        "Homewares",
        "Hardware & Electrical",
        "Kitchen",
        "Restricted Items",
        "Featured",
        "Pest Control",
        "Magazines & Stationery"
    ]
}

nameToCategory = {
    "international": ['International'],
    "world-foods": ['International'],
    "chinese": ['International'],
    "indian": ['International'],
    "japanese": ['International'],
    "korean": ['International'],
    "other-countries": ['International'],
    "south-east-asian": ['International'],
    "thai": ['International'],
    "uk": ['International'],
    "usa": ['International'],
    "fruit-&-veg": ['Fruit and Vegetables'],
    "fresh-fruit": ['Fruit and Vegetables'],
    "fresh-salad-&-herbs": ['Fruit and Vegetables'],
    "fresh-vegetables": ['Fruit and Vegetables'],
    "in-season": ['Fruit and Vegetables'],
    "prepared-fruit-&-veg": ['Fruit and Vegetables'],
    "the-odd-bunch": ['Fruit and Vegetables'],
    "fruit-&-vegetables": ['Fruit and Vegetables'],
    "fresh-cut-fruit": ['Fruit and Vegetables'],
    "fresh-herbs": ['Fruit and Vegetables'],
    "prepacked-fresh-fruit": ['Fruit and Vegetables'],
    "prepacked-fresh-vegetables": ['Fruit and Vegetables'],
    "salad-bags": ['Fruit and Vegetables'],
    "frozen-fruit": ['Fruit and Vegetables'],
    "fruit-snacks": ['Fruit and Vegetables', 'Vegan & Vegetarian', 'Snacks'],
    "vege-snacks": ['Fruit and Vegetables', 'Vegan & Vegetarian', 'Snacks'],
    "olives": ['Fruit and Vegetables', 'Pantry'],
    "pickles": ['Fruit and Vegetables', 'Pantry'],
    "canned-&-dried-vegetables": ['Fruit and Vegetables', 'Pantry'],
    "canned-fruit": ['Fruit and Vegetables', 'Pantry'],
    "vegetable-juices": ['Fruit and Vegetables', 'Drinks'],
    "fresh-salads": ['Fruit and Vegetables'],
    "vege-bags": ['Fruit and Vegetables'],
    "freshly-ground-herbs": ['Fruit and Vegetables'],
    "organic": ['Organic'],
    "fresh-organic-milk": ['Organic', 'Dairy and Eggs'],
    "organic-&-gluten-free": ['Organic', 'Bakery'],
    "meat-&-poultry": ['Meat'],
    "meat": ['Meat'],
    "bbq-meat": ['Meat'],
    "beef": ['Meat'],
    "chicken-&-poultry": ['Meat'],
    "lamb": ['Meat'],
    "mince-&-patties": ['Meat'],
    "offal-&-bones": ['Meat'],
    "pork": ['Meat'],
    "roast-meat": ['Meat'],
    "sausages": ['Meat'],
    "venison-&-game": ['Meat'],
    "butchery": ['Meat'],
    "fresh-beef-&-lamb": ['Meat'],
    "fresh-chicken-&-poultry": ['Meat'],
    "fresh-pork": ['Meat'],
    "fresh-sausages": ['Meat'],
    "fresh-venison-&-game-meat": ['Meat'],
    "precooked-sausages": ['Meat'],
    "prepacked-beef-&-lamb": ['Meat'],
    "prepacked-chicken-&-poultry": ['Meat'],
    "prepacked-sausages": ['Meat'],
    "bacon": ['Meat'],
    "continental-sausage-&-salami": ['Meat'],
    "ham-&-pork": ['Meat'],
    "precooked-beef-&-lamb": ['Meat'],
    "precooked-chicken-&-poultry": ['Meat'],
    "frozen-meat": ['Meat', 'Frozen'],
    "frozen-beef-lamb-&-pork": ['Meat'],
    "frozen-chicken-&-poultry": ['Meat'],
    "meat-snacks": ['Meat', 'Snacks'],
    "canned-meat": ['Meat', 'Pantry'],
    "prepacked-pork": ['Meat'],
    "vegan-&-vegetarian": ['Vegan & Vegetarian'],
    "vegan": ['Vegan & Vegetarian'],
    "pams-plant-based": ['Vegan & Vegetarian'],
    "vegan-range": ['Vegan & Vegetarian'],
    "meat-free": ['Vegan & Vegetarian'],
    "frozen-vegetarian": ['Vegan & Vegetarian'],
    "vegetarian": ['Vegan & Vegetarian'],
    "dairy-&-lactose-free": ['Vegan & Vegetarian'],
    "plant-based-alternatives": ['Vegan & Vegetarian'],
    "frozen-meat-alternatives": ['Vegan & Vegetarian', 'Frozen'],
    "rice-cakes": ['Vegan & Vegetarian', 'Snacks'],
    "rice-crackers": ['Vegan & Vegetarian', 'Snacks'],
    "coconut-cream-&-milk": ['Vegan & Vegetarian'],
    "sauces-&-dressings": ['Sauces and Dressings'],
    "condiments-&-dressings": ['Sauces and Dressings'],
    "aioli": ['Sauces and Dressings'],
    "barbeque-sauces": ['Sauces and Dressings'],
    "chilli-&-pepper-sauces": ['Sauces and Dressings'],
    "chutneys": ['Sauces and Dressings'],
    "fruit-sauces": ['Sauces and Dressings'],
    "mayonnaise": ['Sauces and Dressings'],
    "mint-sauces": ['Sauces and Dressings'],
    "mustards": ['Sauces and Dressings'],
    "salad-dressings": ['Sauces and Dressings'],
    "worcestershire-sauces": ['Sauces and Dressings'],
    "sauces-&-pastes": ['Sauces and Dressings', 'Pantry'],
    "sauces-stock-&-marinades": ['Sauces and Dressings'],
    "chilled-pasta-sauces": ['Sauces and Dressings'],
    "marinades": ['Sauces and Dressings'],
    "packet-sauces": ['Sauces and Dressings'],
    "pasta-sauces": ['Sauces and Dressings', 'Pantry'],
    "simmer-&-stir-through-sauces": ['Sauces and Dressings'],
    "soy-sauce": ['Sauces and Dressings', 'Pantry'],
    "specialty-sauces": ['Sauces and Dressings'],
    "stir-fry-sauces": ['Sauces and Dressings'],
    "dips-&-salsas": ['Sauces and Dressings'],
    "relish": ['Sauces and Dressings'],
    "vinegars": ['Sauces and Dressings'],
    "curry-pastes-&-sauces": ['Sauces and Dressings', 'Pantry'],
    "gravies": ['Sauces and Dressings', 'Pantry'],
    "tomato-sauces": ['Sauces and Dressings', 'Pantry'],
    "tartare-&-seafood-sauces": ['Sauces and Dressings'],
    "bulk-buys": ['Bulk Buys'],
    "bulk-foods": ['Bulk Buys'],
    "bulk-&-loose-foods": ['Bulk Buys'],
    "bulk-breakfast-cereals": ['Bulk Buys'],
    "bulk-confectionery": ['Bulk Buys'],
    "bulk-dried-fruit": ['Bulk Buys'],
    "bulk-nuts": ['Bulk Buys'],
    "bulk-seeds-legumes-&-grains": ['Bulk Buys'],
    "bulk-snacks-&-mixes": ['Bulk Buys'],
    "fish-&-sea-food": ['Fish and Seafood'],
    "fish-&-seafood": ['Fish and Seafood'],
    "fresh-fish": ['Fish and Seafood'],
    "prawns-&-seafood": ['Fish and Seafood'],
    "salmon": ['Fish and Seafood'],
    "seafood": ['Fish and Seafood'],
    "fresh-fish-fillets-&-steaks": ['Fish and Seafood'],
    "fresh-seafood": ['Fish and Seafood'],
    "fresh-shellfish": ['Fish and Seafood'],
    "fresh-smoked-fish": ['Fish and Seafood'],
    "frozen-fish-&-seafood": ['Fish and Seafood', 'Frozen'],
    "seafood-salad": ['Fish and Seafood'],
    "frozen-seafood": ['Fish and Seafood', 'Frozen'],
    "frozen-fish": ['Fish and Seafood'],
    "canned-fish": ['Fish and Seafood', 'Pantry'],
    "fresh-fish-heads": ['Fish and Seafood'],
    "fresh-whole-fish": ['Fish and Seafood'],
    "butter-&-spreads": ['Butter & Spreads'],
    "dips-hummus-&-nibbles": ['Butter & Spreads'],
    "dips-pesto-&-pate": ['Butter & Spreads'],
    "hummus": ['Butter & Spreads'],
    "jams-honey-&-spreads": ['Butter & Spreads'],
    "honey": ['Butter & Spreads'],
    "jam-&-marmalade": ['Butter & Spreads'],
    "marmite-&-vegemite": ['Butter & Spreads'],
    "nut-spreads": ['Butter & Spreads'],
    "savoury-spreads": ['Butter & Spreads'],
    "sweet-spreads": ['Butter & Spreads'],
    "salad-&-cooking-oils": ['Butter & Spreads'],
    "avocado-oils": ['Butter & Spreads', 'Pantry'],
    "olive-oils": ['Butter & Spreads', 'Pantry'],
    "dairy-&-eggs": ['Dairy and Eggs'],
    "cheese": ['Dairy and Eggs'],
    "long-life-milk": ['Dairy and Eggs'],
    "milk-&-cream": ['Dairy and Eggs'],
    "yoghurt-&-desserts": ['Dairy and Eggs'],
    "eggs": ['Dairy and Eggs'],
    "flavoured-milk": ['Dairy and Eggs'],
    "fresh-cream": ['Dairy and Eggs'],
    "fresh-milk": ['Dairy and Eggs'],
    "long-life-milk-&-milk-powder": ['Dairy and Eggs', 'Pantry'],
    "sour-cream-&-crème-fraiche": ['Dairy and Eggs'],
    "yoghurt-&-dairy-food": ['Dairy and Eggs'],
    "yoghurt-bases": ['Dairy and Eggs'],
    "cheese-blocks": ['Dairy and Eggs'],
    "cheese-slices": ['Dairy and Eggs'],
    "cottage-cheese": ['Dairy and Eggs'],
    "cream-cheese": ['Dairy and Eggs'],
    "grated-cheese": ['Dairy and Eggs'],
    "specialty-cheeses": ['Dairy and Eggs'],
    "canned-milk-&-cream": ['Dairy and Eggs'],
    "milk-drink-mixes": ['Dairy and Eggs', 'Drinks'],
    "deli": ['Deli'],
    "deli-meats-&-seafood": ['Deli'],
    "deli-salads": ['Deli'],
    "fresh-deli-savouries": ['Deli'],
    "deli-salads-&-cooked-meats": ['Deli'],
    "deli-meats": ['Deli'],
    "deli-cheeseboards": ['Deli'],
    "deli-specialty-cheeses": ['Deli'],
    "deli-cabinet-cheeses": ['Deli'],
    "fridge-&-deli": ['Deli'],
    "drinks": ['Drinks'],
    "juice-&-drinks": ['Drinks'],
    "low-&-no-alcohol": ['Drinks'],
    "coffee": ['Drinks'],
    "juice-&-cordial": ['Drinks'],
    "soft-drinks-&-sports-drinks": ['Drinks'],
    "tea-&-milk-drinks": ['Drinks'],
    "water": ['Drinks'],
    "cold-drinks": ['Drinks'],
    "hot-drinks": ['Drinks'],
    "black-teas": ['Drinks'],
    "chai-teas": ['Drinks'],
    "chocolate-milk-drink-mixes": ['Drinks'],
    "coffee-additives-&-filters": ['Drinks'],
    "coffee-capsules": ['Drinks'],
    "coffee-flavoured-sachets": ['Drinks'],
    "fresh-coffees": ['Drinks'],
    "fruit-&-herbal-teas": ['Drinks'],
    "green-teas": ['Drinks'],
    "instant-coffees": ['Drinks'],
    "malt-milk-drink-mixes": ['Drinks'],
    "frozen-fruit-&-drink": ['Drinks', 'Frozen'],
    "chilled-fruit-juices": ['Drinks'],
    "coconut-water": ['Drinks'],
    "drinking-yoghurt-&-smoothies": ['Drinks'],
    "flavoured-water": ['Drinks'],
    "fruit-drinks-&-juices": ['Drinks'],
    "iced-teas": ['Drinks'],
    "powdered-drinks": ['Drinks'],
    "soft-drinks": ['Drinks'],
    "sparkling-juices": ['Drinks'],
    "sparkling-water": ['Drinks'],
    "sports-&-energy-drinks": ['Drinks'],
    "non-alcoholic": ['Drinks'],
    "squash-syrups-&-cordials": ['Drinks'],
    "still-water": ['Drinks'],
    "coffee-substitutes": ['Drinks'],
    "brewing-supplies": ['Drinks'],
    "easy-meals": ['Easy Meals'],
    "fresh-pastas": ['Easy Meals'],
    "instant-rices": ['Easy Meals'],
    "rice-meals": ['Easy Meals'],
    "frozen-meals-&-snacks": ['Easy Meals', 'Frozen'],
    "frozen-dessert-pastries": ['Easy Meals', 'Bakery'],
    "frozen-ready-meals": ['Easy Meals'],
    "frozen-pies": ['Easy Meals', 'Bakery'],
    "pizza-pastry-&-bread": ['Easy Meals', 'Bakery'],
    "breakfast-on-the-go": ['Easy Meals'],
    "novelty-bars-&-singles": ['Easy Meals', 'Snacks'],
    "baked-beans-&-spaghetti": ['Easy Meals'],
    "canned-&-prepared-foods": ['Easy Meals', 'Pantry'],
    "tinned-foods": ['Easy Meals', 'Pantry'],
    "pasta-pizza-&-pastry": ['Easy Meals'],
    "prepared-meals-&-sides": ['Easy Meals'],
    "meal-kits": ['Easy Meals'],
    "meal-spot": ['Easy Meals'],
    "ready-to-cook": ['Easy Meals'],
    "mexican": ['Easy Meals'],
    "noodle-meals": ['Easy Meals'],
    "pasta-meals": ['Easy Meals'],
    "simply-dinner": ['Easy Meals'],
    "ready-to-eat": ['Easy Meals'],
    "ready-to-heat": ['Easy Meals'],
    "canned-soup": ['Easy Meals'],
    "chilled-pies-&-pastries": ['Easy Meals'],
    "chilled-soups": ['Easy Meals'],
    "packet-soup": ['Easy Meals'],
    "pizza-&-pizza-bases": ['Easy Meals'],
    "ready-meals": ['Easy Meals'],
    "ice-cream-cones-&-wafers": ['Bakery'],
    "bakery": ['Bakery'],
    "bagels-crumpets-&-pancakes": ['Bakery'],
    "baked-in-store": ['Bakery'],
    "buns-rolls-&-bread-sticks": ['Bakery'],
    "cakes-muffins-&-desserts": ['Bakery'],
    "gluten-free-bakery": ['Bakery'],
    "low-carb-&-keto-bakery": ['Bakery'],
    "pastries-croissants-&-biscuits": ['Bakery'],
    "sliced-&-packaged-bread": ['Bakery'],
    "wraps-pita-&-pizza-bases": ['Bakery'],
    "hot-cross-buns": ['Bakery'],
    "fresh-foods-&-bakery": ['Bakery'],
    "biscuits-&-slices": ['Bakery'],
    "bread-rolls-&-buns": ['Bakery'],
    "cakes-&-muffins": ['Bakery'],
    "fresh-biscuits-&-slices": ['Bakery'],
    "fresh-breads-&-rolls": ['Bakery'],
    "fresh-cakes-&-muffins": ['Bakery'],
    "fresh-desserts-&-pastries": ['Bakery'],
    "garlic-&-herb-breads": ['Bakery'],
    "muffin-splits-&-crumpets": ['Bakery'],
    "pies-&-pastries": ['Bakery'],
    "sliced-bread": ['Bakery'],
    "specialty-breads": ['Bakery'],
    "wraps-&-pita-breads": ['Bakery'],
    "frozen-pastry": ['Bakery'],
    "baking": ['Bakery'],
    "baking-supplies-&-sugar": ['Bakery'],
    "baking-additives": ['Bakery'],
    "baking-mixes": ['Bakery'],
    "baking-nuts-&-seeds": ['Bakery'],
    "baking-syrups": ['Bakery'],
    "breadcrumbs-&-coatings": ['Bakery'],
    "cooking-chocolate": ['Bakery'],
    "dried-fruit": ['Bakery'],
    "essences-&-colourings": ['Bakery'],
    "flour": ['Bakery'],
    "icing-&-decorating": ['Bakery'],
    "sugar": ['Bakery'],
    "sugar-substitutes": ['Bakery'],
    "dessert-pastries": ['Bakery'],
    "frozen-bread-&-dough": ['Bakery'],
    "baby-&-child": ['Kids'],
    "kids-&-babies": ['Kids'],
    "baby-food": ['Kids'],
    "bottles-toys-&-accessories": ['Kids'],
    "for-mum": ['Kids'],
    "formula": ['Kids'],
    "nappies-&-wipes": ['Kids'],
    "baby-toddler-&-kids": ['Kids'],
    "baby-care": ['Kids'],
    "baby-bathing-&-skin-care": ['Kids'],
    "baby-dental-care": ['Kids'],
    "baby-formula-&-toddler-food": ['Kids'],
    "baby-hair-care": ['Kids'],
    "baby-health": ['Kids'],
    "baby-wipes": ['Kids'],
    "nappies-&-changing": ['Kids'],
    "nursing-&-feeding": ['Kids'],
    "toys-&-recreation": ['Kids'],
    "pet": ['Pets'],
    "birds-fish-&-small-animals": ['Pets'],
    "cats": ['Pets'],
    "dogs": ['Pets'],
    "pet-health-&-accessories": ['Pets'],
    "pets": ['Pets'],
    "pet-supplies": ['Pets'],
    "cat-accessories": ['Pets'],
    "cat-food": ['Pets'],
    "dog-food": ['Pets'],
    "dog-treats": ['Pets'],
    "bird-supplies": ['Pets'],
    "cat-treats": ['Pets'],
    "dog-accessories": ['Pets'],
    "pet-accessories": ['Pets'],
    "pet-treatments": ['Pets'],
    "small-animal-supplies": ['Pets'],
    "fish-&-aquatic-pet-supplies": ['Pets'],
    "cleaning-products": ['Cleaning, Laundry And Bathroom'],
    "all-purpose-cleaners": ['Cleaning, Laundry And Bathroom'],
    "bathroom-&-shower-cleaners": ['Cleaning, Laundry And Bathroom'],
    "bleaches": ['Cleaning, Laundry And Bathroom'],
    "carpet-&-floor-cleaners": ['Cleaning, Laundry And Bathroom'],
    "cleaning-accessories": ['Cleaning, Laundry And Bathroom'],
    "dishwasher-detergents": ['Cleaning, Laundry And Bathroom'],
    "dishwasher-rinse-&-clean": ['Cleaning, Laundry And Bathroom'],
    "dishwashing-liquid": ['Cleaning, Laundry And Bathroom'],
    "furniture-&-metal-polishes": ['Cleaning, Laundry And Bathroom'],
    "glass-cleaners": ['Cleaning, Laundry And Bathroom'],
    "kitchen-cleaners": ['Cleaning, Laundry And Bathroom'],
    "paper-towels": ['Cleaning, Laundry And Bathroom'],
    "brushes": ['Cleaning, Laundry And Bathroom'],
    "glue-&-adhesives": ['Cleaning, Laundry And Bathroom'],
    "air-fresheners-&-deodorisers": ['Cleaning, Laundry And Bathroom'],
    "household": ['Cleaning, Laundry And Bathroom'],
    "disposable-tableware": ['Cleaning, Laundry And Bathroom'],
    "pest-&-insect-control": ['Cleaning, Laundry And Bathroom'],
    "rubbish-&-vacuum-bags": ['Cleaning, Laundry And Bathroom'],
    "tissues-&-toilet-paper": ['Cleaning, Laundry And Bathroom'],
    "laundry": ['Cleaning, Laundry And Bathroom'],
    "fabric-softeners": ['Cleaning, Laundry And Bathroom'],
    "laundry-liquid-&-capsules": ['Cleaning, Laundry And Bathroom'],
    "laundry-powders": ['Cleaning, Laundry And Bathroom'],
    "laundry-supplies": ['Cleaning, Laundry And Bathroom'],
    "pre-wash-stain-removers": ['Cleaning, Laundry And Bathroom'],
    "car-care": ['Cleaning, Laundry And Bathroom'],
    "shoe-care": ['Cleaning, Laundry And Bathroom'],
    "fine-fabric-washers": ['Cleaning, Laundry And Bathroom'],
    "laundry-soap": ['Cleaning, Laundry And Bathroom'],
    "washing-machine-cleaners": ['Cleaning, Laundry And Bathroom'],
    "tissues-&-cotton-buds": ['Cleaning, Laundry And Bathroom'],
    "cleaning": ['Cleaning, Laundry And Bathroom'],
    "bags": ['Cleaning, Laundry And Bathroom'],
    "bathroom": ['Cleaning, Laundry And Bathroom'],
    "health-&-body": ['Personal Care'],
    "personal-care": ['Personal Care'],
    "bath-shower-&-soap": ['Personal Care'],
    "contraception-&-pregnancy": ['Personal Care'],
    "dental-&-oral-care": ['Personal Care'],
    "eye-&-ear-care": ['Personal Care'],
    "hair-care": ['Personal Care'],
    "make-up-&-nail-care": ['Personal Care'],
    "medical-&-first-aid": ['Personal Care'],
    "period-&-continence-care": ['Personal Care'],
    "shaving-&-hair-removal": ['Personal Care'],
    "skin-care-&-deodorant": ['Personal Care'],
    "beauty-&-grooming": ['Personal Care'],
    "deodorants": ['Personal Care'],
    "face-&-lip-skin-care": ['Personal Care'],
    "hair-care-&-treatments": ['Personal Care'],
    "hair-colouring": ['Personal Care'],
    "hair-styling-&-accessories": ['Personal Care'],
    "hand-&-body-care": ['Personal Care'],
    "makeup-&-cosmetics": ['Personal Care'],
    "oral-health": ['Personal Care'],
    "suncare-&-self-tan": ['Personal Care'],
    "health-&-wellness": ['Personal Care'],
    "adult-care": ['Personal Care'],
    "allergy-&-sinus": ['Personal Care'],
    "cough-cold-&-flu": ['Personal Care'],
    "digestion-nausea-&-laxatives": ['Personal Care'],
    "family-planning": ['Personal Care'],
    "first-aid": ['Personal Care'],
    "pain-relief": ['Personal Care'],
    "sanitary-protection": ['Personal Care'],
    "stop-smoking": ['Personal Care'],
    "vitamins-&-supplements": ['Personal Care'],
    "wellness-&-sports-nutrition": ['Personal Care'],
    "foot-care": ['Personal Care'],
    "vitamins-&-nutrition": ['Personal Care'],
    "sports-&-fitness": ['Personal Care'],
    "snacks": ['Snacks'],
    "biscuits-&-crackers": ['Snacks'],
    "assorted-biscuits-&-crackers": ['Snacks'],
    "biscuits-&-cookies": ['Snacks'],
    "chocolate-biscuits": ['Snacks'],
    "crackers": ['Snacks'],
    "crème-&-jam-biscuits": ['Snacks'],
    "gourmet-biscuits-&-crackers": ['Snacks'],
    "snack-foods": ['Snacks'],
    "snacks-&-sweets": ['Snacks'],
    "chips": ['Snacks'],
    "corn-chips": ['Snacks'],
    "popcorn": ['Snacks'],
    "potato-chips": ['Snacks'],
    "snack-mixes": ['Snacks'],
    "plain-sweet-biscuits": ['Snacks'],
    "bread-snacks": ['Snacks'],
    "cereal-&-snack-bars": ['Snacks'],
    "muesli-bars": ['Snacks'],
    "nut-bars-&-snacks": ['Snacks'],
    "nutritional-bars": ['Snacks'],
    "chewing-gum-&-mints": ['Snacks'],
    "confectionery": ['Snacks'],
    "boxed-chocolates": ['Snacks'],
    "chocolate-blocks": ['Snacks'],
    "chocolate-family-bags": ['Snacks'],
    "lollies-family-bags": ['Snacks'],
    "ready-to-serve-puddings": ['Snacks'],
    "desserts": ['Snacks'],
    "gourmet-confectionery": ['Snacks'],
    "chilled-custards": ['Snacks'],
    "ice-blocks-&-ice-pops": ['Snacks'],
    "jelly-&-powdered-desserts": ['Baking'],
    "cooking-&-bakeware": ['Baking'],
    "food-storage": ['Baking'],
    "food-wraps-&-bags": ['Baking'],
    "kitchenware": ['Baking'],
    "frozen": ['Frozen'],
    "frozen-items": ['Frozen'],
    "frozen-desserts": ['Frozen'],
    "frozen-vegetables": ['Frozen'],
    "chilled-frozen-&-desserts": ['Frozen'],
    "frozen-bavarians-&-cheesecake": ['Frozen'],
    "frozen-fries-&-potatoes": ['Frozen'],
    "frozen-pizza-&-bases": ['Frozen'],
    "frozen-savouries": ['Frozen'],
    "ice": ['Frozen'],
    "ice-cream-&-sorbet": ['Frozen'],
    "frozen-foods": ['Frozen'],
    "frozen-puddings": ['Frozen'],
    "ice-cream-&-frozen-yoghurt": ['Frozen'],
    "beer-&-wine": ['Alcoholic'],
    "alcohol": ['Alcoholic'],
    "beer": ['Alcoholic'],
    "cider": ['Alcoholic'],
    "red-wine": ['Alcoholic'],
    "rose-wine": ['Alcoholic'],
    "sparkling-&-dessert-wine": ['Alcoholic'],
    "white-wine": ['Alcoholic'],
    "liquorice": ['Alcoholic'],
    "beer-cider-&-wine": ['Alcoholic'],
    "beer-&-cider-awards": ['Alcoholic'],
    "cider-&-alcoholic-gingerbeer": ['Alcoholic'],
    "ipa": ['Alcoholic'],
    "lager-&-pilsner": ['Alcoholic'],
    "pale-ale": ['Alcoholic'],
    "beer-&-cider": ['Alcoholic'],
    "american-style-ale": ['Alcoholic'],
    "apple-&-pear-cider": ['Alcoholic'],
    "craft-beer": ['Alcoholic'],
    "lager": ['Alcoholic'],
    "low-&-no-alcohol-beers": ['Alcoholic'],
    "specialty-&-flavoured-beer": ['Alcoholic'],
    "stout-porter-&-black-beer": ['Alcoholic'],
    "wine": ['Alcoholic'],
    "cabernet": ['Alcoholic'],
    "cask-wine": ['Alcoholic'],
    "champagne-&-sparkling-wine": ['Alcoholic'],
    "chardonnay": ['Alcoholic'],
    "low-&-no-alcohol-wines": ['Alcoholic'],
    "merlot": ['Alcoholic'],
    "other-red-wine": ['Alcoholic'],
    "other-white-wine": ['Alcoholic'],
    "pinot-gris": ['Alcoholic'],
    "pinot-noir": ['Alcoholic'],
    "rose": ['Alcoholic'],
    "fruit-&-flavoured-cider": ['Alcoholic'],
    "seltzer": ['Alcoholic'],
    "mixers": ['Alcoholic'],
    "shiraz": ['Alcoholic'],
    "sauvignon-blanc": ['Alcoholic'],
    "british-style-ale": ['Alcoholic'],
    "european-style-ale": ['Alcoholic'],
    "sake": ['Alcoholic'],
    "pantry": ['Pantry'],
    "herbs-spices-&-stock": ['Pantry'],
    "spices-&-seasonings": ['Pantry'],
    "oil-vinegar-&-condiments": ['Pantry'],
    "pasta-noodles-&-grains": ['Pantry'],
    "breakfast-cereals": ['Pantry'],
    "gourmet-oils-&-condiments": ['Pantry'],
    "olives-&-antipasti-mixes": ['Pantry'],
    "specialty-dry-goods": ['Pantry'],
    "specialty-grains-&-seeds": ['Pantry'],
    "hot-cereals": ['Pantry'],
    "muesli": ['Pantry'],
    "pasta-rice-&-noodles": ['Pantry'],
    "dried-pastas": ['Pantry'],
    "noodles": ['Pantry'],
    "cold-cereals": ['Pantry'],
    "flake/fibre-cereals": ['Pantry'],
    "basmati-rices": ['Pantry'],
    "jasmine-rices": ['Pantry'],
    "long-grain-rices": ['Pantry'],
    "short-&-medium-grain-rices": ['Pantry'],
    "wild-&-coloured-rices": ['Pantry'],
    "tomato-pastes-&-purees": ['Pantry'],
    "coconut-oils": ['Pantry'],
    "nut-&-seed-oils": ['Pantry'],
    "oil-sprays": ['Pantry'],
    "other-oils": ['Pantry'],
    "rice-bran-oils": ['Pantry'],
    "vegetable-oils": ['Pantry'],
    "chilli-&-paprika": ['Pantry'],
    "dried-herbs": ['Pantry'],
    "dried-spices": ['Pantry'],
    "garlic-&-ginger": ['Pantry'],
    "salt-&-pepper": ['Pantry'],
    "canned-desserts": ['Pantry'],
    "canned-items": ['Pantry'],
    "cooking-fat": ['Pantry'],
    "shop-fresh-deals": ['Other'],
    "easter-eggs-&-chocolates": ['Other'],
    "easter-feast-essentials": ['Other'],
    "easter": ['Other'],
    "christmas": ['Other'],
    "insect-repellent": ['Other'],
    "garage-&-outdoor": ['Other'],
    "light-bulbs": ['Other'],
    "hooks": ['Other'],
    "tape": ['Other'],
    "electrical": ['Other'],
    "fire-needs": ['Other'],
    "homeware": ['Other'],
    "manchester": ['Other'],
    "party-supplies": ['Other'],
    "stationery-&-entertainment": ['Other'],
    "newspapers": ['Other'],
    "stationery-&-craft": ['Other'],
    "tobacco-papers-&-filters": ['Other'],
    "bbq": ['Other'],
    "gardening-supplies": ['Other'],
    "clothes-pegs": ['Other'],
    "magazines": ['Other'],
    "other": ['Other'],
    "clothing-&-accessories": ['Other'],
    "entertainment-&-gifts": ['Other'],
    "garden-&-garage": ['Other'],
    "homewares": ['Other'],
    "hardware-&-electrical": ['Other'],
    "kitchen": ['Other'],
    "restricted-items": ['Other'],
    "featured": ['Other'],
    "pest-control": ['Other'],
    "magazines-&-stationery": ['Other'],
}

symbols = ['"', "'", ",", "\n", "[", "]", "."]
def transformToKey(category: str) -> str:
    category = category.replace(" and ", " & ").replace(" ", "-").lower()
    for symbol in symbols:
        category = category.replace(symbol, "")
    return category

def transformItem(category: str, stopWords: set) -> str:
    if category[-1] == 's':
        category = category[:-1]

    category = category.replace(" and ", " & ").replace(" ", "-").lower()
    for symbol in symbols:
        category = category.replace(symbol, "")
    sp = category.split("-")
    for s in sp:
        if s in stopWords:
            category = category.replace(s, "")

    return category

def concatCategories(key) -> str:
    prev = key
    key = transformToKey(key)
    if key not in nameToCategory.keys():
        print(prev, key)
        return key
    cat = ""
    for item in nameToCategory[key]:
        cat += (transformToKey(item) + "@")

    return cat[:-1]

# dict = {}
# for key in categoryToNames.keys():
#     for item in categoryToNames[key]:
#         item = transformToKey(item)
#         if item not in dict.keys():
#             dict[item] = []
#         dict[item].append(key)
# out = open("finalCategories.json", mode="w")
# out.write("{\n")
# for key in dict.keys():
#     out.write(f'    "{key}": {dict[key]},\n')
#
# out.write("}")