categories = {"International": [
    "International",
    "World Foods",
    "Chinese",
    "Indian",
    "Japanese",
    "Korean",
    "Other Countries",
    "South East Asian",
    "Thai",
    "UK",
    "USA"
],
    "Fruit and Vegetables": [
        "Fresh Fruit",
        "Fresh Salad & Herbs",
        "Fresh Vegetables",
        "In Season",
        "Prepared Fruit & Veg",
        "The Odd Bunch",
        "Fruit & Vegetables",
        "Fresh Cut Fruit",
        "Fresh Herbs",
        "PrePacked Fresh Fruit",
        "PrePacked Fresh Vegetables",
        "Salad Bags",
        "Frozen Fruit",
        "Fruit Snacks",
        "Vege Snacks",
        "Olives",
        "Pickles",
        "Canned & Dried Vegetables",
        "Canned Fruit",
        "Vegetable Juices",
        "Fresh Salads",
        "Vege Bags",
        "Freshly Ground Herbs"
    ],
    "Organic": [
        "Organic",
        "Fresh Organic Milk",
        "Organic & Gluten Free"
    ],
    "Meat": [
        "Meat",
        "BBQ Meat",
        "Beef",
        "Chicken & Poultry",
        "Lamb",
        "Mince & Patties",
        "Offal & Bones",
        "Pork",
        "Roast Meat",
        "Sausages",
        "Venison & Game",
        "Butchery",
        "Fresh Beef & Lamb",
        "Fresh Chicken & Poultry",
        "Fresh Pork",
        "Fresh Sausages",
        "Fresh Venison & Game Meat",
        "PreCooked Sausages",
        "PrePacked Beef & Lamb",
        "PrePacked Chicken & Poultry",
        "PrePacked Sausages",
        "Bacon",
        "Continental Sausage & Salami",
        "Ham & Pork",
        "PreCooked Beef & Lamb",
        "PreCooked Chicken & Poultry",
        "Frozen Meat",
        "Frozen Beef Lamb & Pork",
        "Frozen Chicken & Poultry",
        "Meat Snacks",
        "Canned Meat",
        "PrePacked Pork"
    ],
    "Vegan & Vegetarian": [
        "Vegan & Vegetarian",
        "Vegan",
        "Pams Plant Based",
        "Vegan range",
        "Meat Free",
        "Frozen Vegetarian",
        "Vegetarian",
        "Dairy & Lactose Free",
        "Plant based alternatives",
        "Frozen Meat Alternatives",
        "Rice Cakes",
        "Rice Crackers",
        "Fruit Snacks",
        "Vege Snacks",
        "Coconut Cream & Milk",
    ],
    "Sauces and Dressings": [
        "sauces and Dressings",
        "Condiments & Dressings",
        "Aioli",
        "Barbeque Sauces",
        "Chilli & Pepper Sauces",
        "Chutneys",
        "Fruit Sauces",
        "Mayonnaise",
        "Mint Sauces",
        "Mustards",
        "Salad Dressings",
        "Worcestershire Sauces",
        "Sauces & Pastes",
        "Sauces Stock & Marinades",
        "Chilled Pasta Sauces",
        "Marinades",
        "Packet Sauces",
        "Pasta Sauces",
        "Simmer & Stir-Through Sauces",
        "Soy Sauce",
        "Specialty Sauces",
        "Stir Fry Sauces",
        "Dips & Salsas",
        "Relish",
        "Vinegars",
        "Curry Pastes & Sauces",
        "Gravies",
        "Tomato Sauces",
        "Tartare & Seafood Sauces"
    ],
    "Bulk Buys": [
        "Bulk Buys",
        "Bulk Foods",
        "Bulk & Loose Foods",
        "Bulk Breakfast Cereals",
        "Bulk Confectionery",
        "Bulk Dried Fruit",
        "Bulk Nuts",
        "Bulk Seeds Legumes & Grains",
        "Bulk Snacks & Mixes"
    ],
    "Fish and Seafood": [
        "Fish and Sea Food",
        "Fresh Fish",
        "Prawns & Seafood",
        "Salmon",
        "Seafood",
        "Fresh Fish Fillets & Steaks",
        "Fresh Seafood",
        "Fresh Shellfish",
        "Fresh Smoked Fish",
        "Frozen Fish & Seafood",
        "Seafood Salad",
        "Frozen Seafood",
        "Frozen Fish",
        "Canned Fish",
        "Fresh Fish Heads",
        "Fresh Whole Fish"
    ],
    "Butter & Spreads": [
        "Butter & Spreads",
        "Dips Hummus & Nibbles",
        "Dips Pesto & Pate",
        "Hummus",
        "Jams Honey & Spreads",
        "Honey",
        "Jam & Marmalade",
        "Marmite & Vegemite",
        "Nut Spreads",
        "Savoury Spreads",
        "Sweet Spreads",
        "Salad & Cooking Oils",
        "Avocado Oils",
        "Olive Oils"
    ],
    "Dairy and Eggs": [
        "Dairy and Eggs",
        "Cheese",
        "Long Life Milk",
        "Milk & Cream",
        "Yoghurt & Desserts",
        "Eggs",
        "Flavoured Milk",
        "Fresh Cream",
        "Fresh Milk",
        "Fresh Organic Milk",
        "Long Life Milk & Milk Powder",
        "Sour Cream & Crème Fraiche",
        "Yoghurt & Dairy Food",
        "Yoghurt Bases",
        "Cheese Blocks",
        "Cheese Slices",
        "Cottage Cheese",
        "Cream Cheese",
        "Grated Cheese",
        "Specialty Cheeses",
        "Canned Milk & Cream",
        "Milk Drink Mixes"
    ],
    "Deli": [
        "Deli",
        "Deli Meats & Seafood",
        "Deli Salads",
        "Fresh Deli Savouries",
        "Deli Salads & Cooked Meats",
        "Deli Meats",
        "Deli Cheeseboards",
        "Deli Specialty Cheeses",
        "Deli Cabinet Cheeses"
    ],
    "Drinks": [
        "Drinks",
        "Juice & Drinks",
        "Low & no alcohol",
        "Coffee",
        "Juice & Cordial",
        "Soft Drinks & Sports Drinks",
        "Tea & Milk Drinks",
        "Water",
        "Cold Drinks",
        "Hot Drinks",
        "Black Teas",
        "Chai Teas",
        "Chocolate Milk Drink Mixes",
        "Coffee Additives & Filters",
        "Coffee Capsules",
        "Coffee Flavoured Sachets",
        "Fresh Coffees",
        "Fruit & Herbal Teas",
        "Green Teas",
        "Instant Coffees",
        "Malt Milk Drink Mixes",
        "Frozen Fruit & Drink",
        "Chilled Fruit Juices",
        "Coconut Water",
        "Drinking Yoghurt & Smoothies",
        "Flavoured Water",
        "Fruit Drinks & Juices",
        "Iced Teas",
        "Powdered Drinks",
        "Soft Drinks",
        "Sparkling Juices",
        "Sparkling Water",
        "Sports & Energy Drinks",
        "Non Alcoholic",
        "Vegetable Juices",
        "Squash Syrups & Cordials",
        "Milk Drink Mixes",
        "Still Water",
        "Coffee Substitutes",
        "Brewing Supplies"
    ],
    "Easy Meals": [
        "Easy Meals",
        "Fresh Pastas",
        "Instant Rices",
        "Rice Meals",
        "Frozen Meals & Snacks",
        "Frozen Dessert Pastries",
        "Frozen Ready Meals",
        "Frozen Pies",
        "Pizza Pastry & Bread",
        "Breakfast On The Go",
        "Novelty Bars & Singles",
        "Baked Beans & Spaghetti",
        "Canned & Prepared Foods",
        "Tinned Foods",
        "Pasta Pizza & Pastry",
        "Prepared Meals & Sides",
        "Meal Kits",
        "Meal Spot",
        "Ready to Cook",
        "Mexican",
        "Noodle Meals",
        "Pasta Meals",
        "Simply DINNER",
        "Ready to Eat",
        "Ready to Heat",
        "Canned Soup",
        "Chilled Pies & Pastries",
        "Chilled Soups",
        "Packet Soup",
        "Pizza & Pizza Bases",
        "Ready Meals"
    ],
    "Bakery": [
        "Ice Cream Cones & Wafers",
        "Bakery",
        "Bagels Crumpets & Pancakes",
        "Baked In Store",
        "Buns Rolls & Bread Sticks",
        "Cakes Muffins & Desserts",
        "Gluten Free Bakery",
        "Low Carb & Keto Bakery",
        "Pastries Croissants & Biscuits",
        "Sliced & Packaged Bread",
        "Wraps Pita & Pizza Bases",
        "Hot Cross Buns",
        "Fresh Foods & Bakery",
        "Biscuits & Slices",
        "Bread Rolls & Buns",
        "Cakes & Muffins",
        "Fresh Biscuits & Slices",
        "Fresh Breads & Rolls",
        "Fresh Cakes & Muffins",
        "Fresh Desserts & Pastries",
        "Garlic & Herb Breads",
        "Muffin Splits & Crumpets",
        "Pies & Pastries",
        "Sliced Bread",
        "Specialty Breads",
        "Wraps & Pita Breads",
        "Organic & Gluten Free",
        "Frozen Dessert Pastries",
        "Frozen Pastry",
        "Frozen Pies",
        "Baking",
        "Baking Supplies & Sugar",
        "Pizza Pastry & Bread",
        "Baking Additives",
        "Baking Mixes",
        "Baking Nuts & Seeds",
        "Baking Syrups",
        "Breadcrumbs & Coatings",
        "Cooking Chocolate",
        "Dried Fruit",
        "Essences & Colourings",
        "Flour",
        "Icing & Decorating",
        "Sugar",
        "Sugar Substitutes",
        "Dessert Pastries",
        "Frozen Bread & Dough"
    ],
    "Kids": [
        "Kids and Babies",
        "Baby Food",
        "Bottles Toys & Accessories",
        "For Mum",
        "Formula",
        "Nappies & Wipes",
        "Baby Toddler & Kids",
        "Baby Care",
        "Baby Bathing & Skin Care",
        "Baby Dental Care",
        "Baby Formula & Toddler Food",
        "Baby Hair Care",
        "Baby Health",
        "Baby Wipes",
        "Nappies & Changing",
        "Nursing & Feeding",
        "Toys & Recreation"
    ],
    "Pets": [
        "Birds Fish & Small Animals",
        "Cats",
        "Dogs",
        "Pet health & accessories",
        "Pets",
        "Pet Supplies",
        "Cat Accessories",
        "Cat Food",
        "Dog Food",
        "Dog Treats",
        "Bird Supplies",
        "Cat Treats",
        "Dog Accessories",
        "Pet Accessories",
        "Pet Treatments",
        "Small Animal Supplies",
        "Fish & Aquatic Pet Supplies"
    ],
    "Cleaning, Laundry And Bathroom": [
        "Cleaning Products",
        "All Purpose Cleaners",
        "Bathroom & Shower Cleaners",
        "Bleaches",
        "Carpet & Floor Cleaners",
        "Cleaning Accessories",
        "Dishwasher Detergents",
        "Dishwasher Rinse & Clean",
        "Dishwashing Liquid",
        "Furniture & Metal Polishes",
        "Glass Cleaners",
        "Kitchen Cleaners",
        "Paper Towels",
        "Brushes",
        "Glue & Adhesives",
        "Air Fresheners & Deodorisers",
        "Household",
        "Disposable Tableware",
        "Pest & Insect Control",
        "Rubbish & Vacuum Bags",
        "Tissues & Toilet Paper",
        "Laundry",
        "Fabric Softeners",
        "Laundry Liquid & Capsules",
        "Laundry Powders",
        "Laundry Supplies",
        "Pre Wash Stain Removers",
        "Car Care",
        "Shoe Care",
        "Fine Fabric Washers",
        "Laundry Soap",
        "Washing Machine Cleaners",
        "Tissues & Cotton Buds",
        "Cleaning",
        "Bags",
        "Bathroom"
    ],
    "Personal Care": [
        "Personal Care",
        "Bath Shower & Soap",
        "Contraception & Pregnancy",
        "Dental & Oral Care",
        "Eye & Ear Care",
        "Hair Care",
        "Make Up & Nail Care",
        "Medical & First Aid",
        "Period & Continence Care",
        "Shaving & Hair Removal",
        "Skin Care & Deodorant",
        "Beauty & Grooming",
        "Deodorants",
        "Face & Lip Skin Care",
        "Hair Care & Treatments",
        "Hair Colouring",
        "Hair Styling & Accessories",
        "Hand & Body Care",
        "Makeup & Cosmetics",
        "Oral Health",
        "Suncare & Self Tan",
        "Health & Wellness",
        "Adult Care",
        "Allergy & Sinus",
        "Cough Cold & Flu",
        "Digestion Nausea & Laxatives",
        "Family Planning",
        "First Aid",
        "Pain Relief",
        "Sanitary Protection",
        "Stop Smoking",
        "Vitamins & Supplements",
        "Wellness & Sports Nutrition",
        "Foot Care",
        "Vitamins & Nutrition",
        "Sports & Fitness"
    ],
    "Snacks": [
        "Snacks",
        "Biscuits & Crackers",
        "Assorted Biscuits & Crackers",
        "Biscuits & Cookies",
        "Chocolate Biscuits",
        "Crackers",
        "Crème & Jam Biscuits",
        "Gourmet Biscuits & Crackers",
        "Snack Foods",
        "Snacks & Sweets",
        "Chips",
        "Corn Chips",
        "Meat Snacks",
        "Popcorn",
        "Potato Chips",
        "Snack Mixes",
        "Rice Cakes",
        "Rice Crackers",
        "Fruit Snacks",
        "Vege Snacks",
        "Plain Sweet Biscuits",
        "Bread Snacks",
        "Cereal & Snack Bars",
        "Muesli Bars",
        "Nut Bars & Snacks",
        "Nutritional Bars",
        "Chewing Gum & Mints",
        "Confectionery",
        "Boxed Chocolates",
        "Chocolate Blocks",
        "Chocolate Family Bags",
        "Lollies Family Bags",
        "Ready To Serve Puddings",
        "Desserts",
        "Novelty Bars & Singles",
        "Gourmet Confectionery",
        "Chilled Custards",
        "Ice Blocks & Ice Pops"
    ],
    "Baking": [
        "Jelly & Powdered Desserts",
        "Cooking & Bakeware",
        "Food Storage",
        "Food Wraps & Bags",
        "Kitchenware"
    ],
    "Frozen": [
        "Frozen Fish & Seafood",
        "Frozen Items",
        "Frozen Desserts",
        "Frozen Fruit & Drink",
        "Frozen Meals & Snacks",
        "Frozen Meat",
        "Frozen Meat Alternatives",
        "Frozen Seafood",
        "Frozen Vegetables",
        "Chilled Frozen & Desserts",
        "Frozen Bavarians & Cheesecake",
        "Frozen Fries & Potatoes",
        "Frozen Pizza & Bases",
        "Frozen Savouries",
        "Ice",
        "Ice Cream & Sorbet",
        "Frozen Foods",
        "Frozen Puddings",
        "Ice Cream & Frozen Yoghurt"
    ],
    "Alcoholic": [
        "Alcohol",
        "Beer",
        "Cider",
        "Red wine",
        "Rose wine",
        "Sparkling & dessert wine",
        "White wine",
        "Liquorice",
        "Beer Cider & Wine",
        "Beer & Cider Awards",
        "Cider & Alcoholic Gingerbeer",
        "IPA",
        "Lager & Pilsner",
        "Pale Ale",
        "Beer & Cider",
        "American-style Ale",
        "Apple & Pear Cider",
        "Craft Beer",
        "Lager",
        "Low & No Alcohol Beers",
        "Specialty & Flavoured Beer",
        "Stout Porter & Black Beer",
        "Wine",
        "Cabernet",
        "Cask Wine",
        "Champagne & Sparkling Wine",
        "Chardonnay",
        "Low & No Alcohol Wines",
        "Merlot",
        "Other Red Wine",
        "Other White Wine",
        "Pinot Gris",
        "Pinot Noir",
        "Rose",
        "Fruit & Flavoured Cider",
        "Seltzer",
        "Mixers",
        "Shiraz",
        "Sauvignon Blanc",
        "British-style Ale",
        "European-style Ale",
        "Sake"
    ],
    "Pantry": [
        "Sauces & Pastes",
        "Soy Sauce",
        "Pasta Sauces",
        "Long Life Milk & Milk Powder",
        "Herbs Spices & Stock",
        "Oil Vinegar & Condiments",
        "Pasta Noodles & Grains",
        "Breakfast Cereals",
        "Gourmet Oils & Condiments",
        "Olives & Antipasti Mixes",
        "Pantry",
        "Specialty Dry Goods",
        "Olives",
        "Pickles",
        "Specialty Grains & Seeds",
        "Hot Cereals",
        "Muesli",
        "Pasta Rice & Noodles",
        "Dried Pastas",
        "Noodles",
        "Cold Cereals",
        "Flake/Fibre Cereals",
        "Basmati Rices",
        "Jasmine Rices",
        "Long Grain Rices",
        "Short & Medium Grain Rices",
        "Wild & Coloured Rices",
        "Curry Pastes & Sauces",
        "Gravies",
        "Tomato Pastes & Purees",
        "Tomato Sauces",
        "Avocado Oils",
        "Coconut Oils",
        "Nut & Seed Oils",
        "Oil Sprays",
        "Olive Oils",
        "Other Oils",
        "Rice Bran Oils",
        "Vegetable Oils",
        "Chilli & Paprika",
        "Dried Herbs",
        "Dried Spices",
        "Garlic & Ginger",
        "Salt & Pepper",
        "Canned Desserts",
        "Canned Items",
        "Canned & Dried Vegetables",
        "Canned Fruit",
        "Canned Meat",
        "Canned & Prepared Foods",
        "Tinned Foods",
        "Canned Fish",
        "Cooking Fat"
    ],
    "Other": [
        "Shop Fresh Deals",
        "Easter eggs and chocolates",
        "Easter feast essentials",
        "Easter",
        "Christmas",
        "Insect Repellent",
        "Garage & Outdoor",
        "Light Bulbs",
        "Hooks",
        "Tape",
        "Electrical",
        "Fire Needs",
        "Homeware",
        "Manchester",
        "Party Supplies",
        "Stationery & Entertainment",
        "Newspapers",
        "Stationery & Craft",
        "Tobacco Papers & Filters",
        "BBQ",
        "Gardening Supplies",
        "Clothes Pegs",
        "Magazines",
        "Other",
        "Clothing & Accessories",
        "Entertainment & Gifts",
        "Garden & Garage",
        "Homewares",
        "Hardware & Electrical",
        "Kitchen",
        "Restricted Items",
        "Featured",
        "Pest Control",
        "Magazines & Stationery"
    ]
}
